addons:
  apt:
    update: true
    packages:
    - libpcap-dev
language: c
compiler:
  - clang
  - gcc
script:
  - cd hexdump
  - sh autogen.sh
  - mkdir build
  - cd build
  - ../configure --enable-warn-all
  - make
  - ( cd test && make cobadpkts ) || true
  - make test
  - ./hexdump -h
